# Generated by Django 4.1.1 on 2023-01-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcourses',
            name='session',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
