# Generated by Django 4.1.1 on 2023-01-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_assignedcourses_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcourses',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
