# Generated by Django 4.1.1 on 2023-01-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_assignedcourses_is_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcourses',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
